import {StyleSheet} from "react-native";
import {COLORS} from "../../../../styles/COLORS";

export const styles = StyleSheet.create({
    scrollContainer: {
        flexGrow: 1,
        backgroundColor: '#ffffff',
    },
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    registerContainer: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 20,
        backgroundColor: '#ffffff',
    },
    title: {
        fontSize: 28,
        fontWeight: '700',
        color: '#1a202c',
        marginBottom: 20,
        textAlign: 'center',
        letterSpacing: -0.5,
        paddingHorizontal: 24,
    },
    label: {
        fontSize: 16,
        color: '#2d3748',
        marginBottom: 8,
        fontWeight: '600',
        marginLeft: 4,
    },
    input: {
        height: 56,
        borderColor: '#e2e8f0',
        borderWidth: 2,
        borderRadius: 12,
        paddingHorizontal: 16,
        marginBottom: 20,
        fontSize: 16,
        backgroundColor: '#ffffff',
        color: '#2d3748',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    inputFocused: {
        borderColor: COLORS.domitsHostBlue,
        shadowColor: COLORS.domitsHostBlue,
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    passwordRequirements: {
        marginBottom: 20,
        padding: 16,
        backgroundColor: '#f7fafc',
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: COLORS.domitsHostBlue,
    },
    requirementText: {
        fontSize: 14,
        color: '#4a5568',
        marginBottom: 4,
        lineHeight: 20,
    },
    asHostCheckBox: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 25,
        padding: 16,
        backgroundColor: '#f7fafc',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    errorText: {
        color: '#e53e3e',
        fontSize: 14,
        marginBottom: 15,
        marginTop: -10,
        marginLeft: 4,
        fontWeight: '500',
    },
    // Sign up button
    signUpButton: {
        backgroundColor: COLORS.domitsHostBlue,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        flex: 1,
        marginLeft: 10,
        shadowColor: COLORS.domitsHostBlue,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    nextButton: {
        backgroundColor: COLORS.domitsHostBlue,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 25,
        shadowColor: COLORS.domitsHostBlue,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    backButton: {
        backgroundColor: '#718096',
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        flex: 1,
        marginRight: 10,
        shadowColor: '#718096',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    buttonContainer: {
        flexDirection: 'row',
        marginTop: 25,
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    backButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.3,
    },
    // Progress indicator styles
    progressContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 20,
        paddingHorizontal: 24,
    },
    progressStep: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 8,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    progressStepActive: {
        backgroundColor: COLORS.domitsHostBlue,
    },
    progressStepInactive: {
        backgroundColor: '#e2e8f0',
    },
    progressStepText: {
        fontSize: 16,
        fontWeight: '700',
    },
    progressStepTextActive: {
        color: 'white',
    },
    progressStepTextInactive: {
        color: '#a0aec0',
    },
    // Step title styles
    stepTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1a202c',
        marginBottom: 20,
        textAlign: 'center',
        letterSpacing: -0.5,
        paddingHorizontal: 24,
    },
    // Helper text styles
    helperText: {
        fontSize: 14,
        color: '#718096',
        marginBottom: 15,
        textAlign: 'center',
        lineHeight: 20,
        paddingHorizontal: 24,
    },
});