export const PUBLIC_BOOKING_REQUEST_ERROR_CODES = Object.freeze({
  INVALID_REQUEST: "invalid_request",
  MISSING_IDEMPOTENCY_KEY: "missing_idempotency_key",
  INVALID_IDEMPOTENCY_KEY: "invalid_idempotency_key",
  INVALID_GUEST_CONTACT: "invalid_guest_contact",
  INVALID_GUEST_COUNT: "invalid_guest_count",
  INVALID_DATE_RANGE: "invalid_date_range",
  QUOTE_TOKEN_INVALID: "quote_token_invalid",
  SITE_NOT_FOUND: "site_not_found",
  SITE_NOT_PUBLISHED: "site_not_published",
  UNAVAILABLE_DATES: "unavailable_dates",
  STAY_RESTRICTION_VIOLATION: "stay_restriction_violation",
  QUOTE_EXPIRED: "quote_expired",
  SITE_SUSPENDED: "site_suspended",
  QUOTE_UNAVAILABLE: "quote_unavailable",
  IDEMPOTENCY_KEY_REUSED: "idempotency_key_reused",
  PRICING_SERVICE_UNAVAILABLE: "pricing_service_unavailable",
  BOOKING_SERVICE_UNAVAILABLE: "booking_service_unavailable",
  INTERNAL_ERROR: "internal_error",
});

const STATUS_CODE_BY_ERROR_CODE = Object.freeze({
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.INVALID_REQUEST]: 400,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.MISSING_IDEMPOTENCY_KEY]: 400,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.INVALID_IDEMPOTENCY_KEY]: 400,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.INVALID_GUEST_CONTACT]: 400,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.INVALID_GUEST_COUNT]: 400,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.INVALID_DATE_RANGE]: 400,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.QUOTE_TOKEN_INVALID]: 401,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.SITE_NOT_FOUND]: 404,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.SITE_NOT_PUBLISHED]: 409,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.UNAVAILABLE_DATES]: 409,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.STAY_RESTRICTION_VIOLATION]: 409,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.QUOTE_EXPIRED]: 409,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.SITE_SUSPENDED]: 410,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.QUOTE_UNAVAILABLE]: 422,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.IDEMPOTENCY_KEY_REUSED]: 422,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.PRICING_SERVICE_UNAVAILABLE]: 503,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.BOOKING_SERVICE_UNAVAILABLE]: 503,
  [PUBLIC_BOOKING_REQUEST_ERROR_CODES.INTERNAL_ERROR]: 500,
});

const QUOTE_ENDPOINT_PASSTHROUGH_CODES = new Set([
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.INVALID_GUEST_COUNT,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.INVALID_DATE_RANGE,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.UNAVAILABLE_DATES,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.STAY_RESTRICTION_VIOLATION,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.QUOTE_UNAVAILABLE,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.PRICING_SERVICE_UNAVAILABLE,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.SITE_NOT_FOUND,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.SITE_NOT_PUBLISHED,
  PUBLIC_BOOKING_REQUEST_ERROR_CODES.SITE_SUSPENDED,
]);

export class PublicBookingRequestError extends Error {
  constructor(code, message) {
    const statusCode = STATUS_CODE_BY_ERROR_CODE[code];
    if (!statusCode) {
      throw new TypeError(`Unknown public booking request error code: ${code}`);
    }
    super(message);
    this.name = "PublicBookingRequestError";
    this.code = code;
    this.statusCode = statusCode;
  }
}

export const publicBookingRequestErrorFromQuoteError = (quoteError) => {
  const code = String(quoteError?.code || "");
  if (QUOTE_ENDPOINT_PASSTHROUGH_CODES.has(code)) {
    return new PublicBookingRequestError(code, String(quoteError?.message || "The quote could not be confirmed."));
  }
  return new PublicBookingRequestError(
    PUBLIC_BOOKING_REQUEST_ERROR_CODES.BOOKING_SERVICE_UNAVAILABLE,
    "Live pricing and availability could not be confirmed. Please try again."
  );
};
