import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
  },
  image: {
    marginTop: 70,
    alignSelf: 'center',
    width: '90%',
    height: '100%',
    maxHeight: 100,
    borderRadius: 20,
  },
  confirmedContainer: {
    alignSelf: 'center',
    width: '90%',
    height: '100%',
    borderRadius: 20,
    backgroundColor: '#0D9813',
  },
  confirmedContent: {
    position: 'absolute',
    top: 10,
    left: 10,
    width: '95%',
    display: 'flex',
  },
  confirmedLabel: {
    color: 'white',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 24,
  },
  confirmedTextContent: {
    color: 'white',
    fontWeight: '800',
    fontSize: 12,
    lineHeight: 24,
  },
  contentContainer: {
    alignSelf: 'center',
    width: '90%',
    height: '100%',
    borderRadius: 20,
    backgroundColor: 'white',
    // iOS shadow properties
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.5,
    // Android shadow properties
    elevation: 4,
  },
  content: {
    position: 'absolute',
    top: 10,
    left: 10,
    width: '95%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    color: 'black',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 24,
  },
  textContent: {
    color: 'black',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 24,
  },
  locationContainer: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  locationContent: {
    position: 'absolute',
    top: 10,
    left: 10,
    width: '95%',
    display: 'flex',
  },
  locationLabel: {
    color: 'black',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 24,
  },
  locationTextContent: {
    color: 'black',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 24,
  },
  viewBookingButton: {
    alignSelf: 'center',
    width: '85%',
    height: 40,
    backgroundColor: '#0D9813',
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
});
