import { toDestinationSlug } from "./destinationSlug.js";

const CONTINENTS = Object.freeze({
  africa: "Africa",
  antarctica: "Antarctica",
  asia: "Asia",
  caribbean: "Caribbean",
  europe: "Europe",
  "north-america": "North America",
  oceania: "Oceania",
  "south-america": "South America",
});

const COUNTRIES = Object.freeze([
  ["AD", "Andorra", "europe"],
  ["AE", "United Arab Emirates", "asia"],
  ["AF", "Afghanistan", "asia"],
  ["AG", "Antigua and Barbuda", "caribbean"],
  ["AI", "Anguilla", "caribbean"],
  ["AL", "Albania", "europe"],
  ["AM", "Armenia", "asia"],
  ["AO", "Angola", "africa"],
  ["AQ", "Antarctica", "antarctica"],
  ["AR", "Argentina", "south-america"],
  ["AS", "American Samoa", "oceania"],
  ["AT", "Austria", "europe"],
  ["AU", "Australia", "oceania"],
  ["AW", "Aruba", "caribbean"],
  ["AX", "Åland Islands", "europe"],
  ["AZ", "Azerbaijan", "asia"],
  ["BA", "Bosnia and Herzegovina", "europe"],
  ["BB", "Barbados", "caribbean"],
  ["BD", "Bangladesh", "asia"],
  ["BE", "Belgium", "europe"],
  ["BF", "Burkina Faso", "africa"],
  ["BG", "Bulgaria", "europe"],
  ["BH", "Bahrain", "asia"],
  ["BI", "Burundi", "africa"],
  ["BJ", "Benin", "africa"],
  ["BL", "Saint Barthélemy", "caribbean"],
  ["BM", "Bermuda", "north-america"],
  ["BN", "Brunei Darussalam", "asia"],
  ["BO", "Bolivia, Plurinational State of", "south-america"],
  ["BQ", "Bonaire, Sint Eustatius and Saba", "caribbean"],
  ["BR", "Brazil", "south-america"],
  ["BS", "Bahamas", "caribbean"],
  ["BT", "Bhutan", "asia"],
  ["BV", "Bouvet Island", "antarctica"],
  ["BW", "Botswana", "africa"],
  ["BY", "Belarus", "europe"],
  ["BZ", "Belize", "north-america"],
  ["CA", "Canada", "north-america"],
  ["CC", "Cocos (Keeling) Islands", "oceania"],
  ["CD", "Congo, Democratic Republic of the", "africa"],
  ["CF", "Central African Republic", "africa"],
  ["CG", "Congo", "africa"],
  ["CH", "Switzerland", "europe"],
  ["CI", "Côte d'Ivoire", "africa"],
  ["CK", "Cook Islands", "oceania"],
  ["CL", "Chile", "south-america"],
  ["CM", "Cameroon", "africa"],
  ["CN", "China", "asia"],
  ["CO", "Colombia", "south-america"],
  ["CR", "Costa Rica", "north-america"],
  ["CU", "Cuba", "caribbean"],
  ["CV", "Cabo Verde", "africa"],
  ["CW", "Curaçao", "caribbean"],
  ["CX", "Christmas Island", "oceania"],
  ["CY", "Cyprus", "europe"],
  ["CZ", "Czechia", "europe"],
  ["DE", "Germany", "europe"],
  ["DJ", "Djibouti", "africa"],
  ["DK", "Denmark", "europe"],
  ["DM", "Dominica", "caribbean"],
  ["DO", "Dominican Republic", "caribbean"],
  ["DZ", "Algeria", "africa"],
  ["EC", "Ecuador", "south-america"],
  ["EE", "Estonia", "europe"],
  ["EG", "Egypt", "africa"],
  ["EH", "Western Sahara", "africa"],
  ["ER", "Eritrea", "africa"],
  ["ES", "Spain", "europe"],
  ["ET", "Ethiopia", "africa"],
  ["FI", "Finland", "europe"],
  ["FJ", "Fiji", "oceania"],
  ["FK", "Falkland Islands (Malvinas)", "south-america"],
  ["FM", "Micronesia, Federated States of", "oceania"],
  ["FO", "Faroe Islands", "europe"],
  ["FR", "France", "europe"],
  ["GA", "Gabon", "africa"],
  ["GB", "United Kingdom", "europe"],
  ["GD", "Grenada", "caribbean"],
  ["GE", "Georgia", "asia"],
  ["GF", "French Guiana", "south-america"],
  ["GG", "Guernsey", "europe"],
  ["GH", "Ghana", "africa"],
  ["GI", "Gibraltar", "europe"],
  ["GL", "Greenland", "north-america"],
  ["GM", "Gambia", "africa"],
  ["GN", "Guinea", "africa"],
  ["GP", "Guadeloupe", "caribbean"],
  ["GQ", "Equatorial Guinea", "africa"],
  ["GR", "Greece", "europe"],
  ["GS", "South Georgia and the South Sandwich Islands", "antarctica"],
  ["GT", "Guatemala", "north-america"],
  ["GU", "Guam", "oceania"],
  ["GW", "Guinea-Bissau", "africa"],
  ["GY", "Guyana", "south-america"],
  ["HK", "Hong Kong", "asia"],
  ["HM", "Heard Island and McDonald Islands", "antarctica"],
  ["HN", "Honduras", "north-america"],
  ["HR", "Croatia", "europe"],
  ["HT", "Haiti", "caribbean"],
  ["HU", "Hungary", "europe"],
  ["ID", "Indonesia", "asia"],
  ["IE", "Ireland", "europe"],
  ["IL", "Israel", "asia"],
  ["IM", "Isle of Man", "europe"],
  ["IN", "India", "asia"],
  ["IO", "British Indian Ocean Territory", "asia"],
  ["IQ", "Iraq", "asia"],
  ["IR", "Iran, Islamic Republic of", "asia"],
  ["IS", "Iceland", "europe"],
  ["IT", "Italy", "europe"],
  ["JE", "Jersey", "europe"],
  ["JM", "Jamaica", "caribbean"],
  ["JO", "Jordan", "asia"],
  ["JP", "Japan", "asia"],
  ["KE", "Kenya", "africa"],
  ["KG", "Kyrgyzstan", "asia"],
  ["KH", "Cambodia", "asia"],
  ["KI", "Kiribati", "oceania"],
  ["KM", "Comoros", "africa"],
  ["KN", "Saint Kitts and Nevis", "caribbean"],
  ["KP", "Korea, Democratic People's Republic of", "asia"],
  ["KR", "Korea, Republic of", "asia"],
  ["KW", "Kuwait", "asia"],
  ["KY", "Cayman Islands", "caribbean"],
  ["KZ", "Kazakhstan", "asia"],
  ["LA", "Lao People's Democratic Republic", "asia"],
  ["LB", "Lebanon", "asia"],
  ["LC", "Saint Lucia", "caribbean"],
  ["LI", "Liechtenstein", "europe"],
  ["LK", "Sri Lanka", "asia"],
  ["LR", "Liberia", "africa"],
  ["LS", "Lesotho", "africa"],
  ["LT", "Lithuania", "europe"],
  ["LU", "Luxembourg", "europe"],
  ["LV", "Latvia", "europe"],
  ["LY", "Libya", "africa"],
  ["MA", "Morocco", "africa"],
  ["MC", "Monaco", "europe"],
  ["MD", "Moldova, Republic of", "europe"],
  ["ME", "Montenegro", "europe"],
  ["MF", "Saint Martin (French part)", "caribbean"],
  ["MG", "Madagascar", "africa"],
  ["MH", "Marshall Islands", "oceania"],
  ["MK", "North Macedonia", "europe"],
  ["ML", "Mali", "africa"],
  ["MM", "Myanmar", "asia"],
  ["MN", "Mongolia", "asia"],
  ["MO", "Macao", "asia"],
  ["MP", "Northern Mariana Islands", "oceania"],
  ["MQ", "Martinique", "caribbean"],
  ["MR", "Mauritania", "africa"],
  ["MS", "Montserrat", "caribbean"],
  ["MT", "Malta", "europe"],
  ["MU", "Mauritius", "africa"],
  ["MV", "Maldives", "asia"],
  ["MW", "Malawi", "africa"],
  ["MX", "Mexico", "north-america"],
  ["MY", "Malaysia", "asia"],
  ["MZ", "Mozambique", "africa"],
  ["NA", "Namibia", "africa"],
  ["NC", "New Caledonia", "oceania"],
  ["NE", "Niger", "africa"],
  ["NF", "Norfolk Island", "oceania"],
  ["NG", "Nigeria", "africa"],
  ["NI", "Nicaragua", "north-america"],
  ["NL", "Netherlands", "europe"],
  ["NO", "Norway", "europe"],
  ["NP", "Nepal", "asia"],
  ["NR", "Nauru", "oceania"],
  ["NU", "Niue", "oceania"],
  ["NZ", "New Zealand", "oceania"],
  ["OM", "Oman", "asia"],
  ["PA", "Panama", "north-america"],
  ["PE", "Peru", "south-america"],
  ["PF", "French Polynesia", "oceania"],
  ["PG", "Papua New Guinea", "oceania"],
  ["PH", "Philippines", "asia"],
  ["PK", "Pakistan", "asia"],
  ["PL", "Poland", "europe"],
  ["PM", "Saint Pierre and Miquelon", "north-america"],
  ["PN", "Pitcairn", "oceania"],
  ["PR", "Puerto Rico", "caribbean"],
  ["PS", "Palestine, State of", "asia"],
  ["PT", "Portugal", "europe"],
  ["PW", "Palau", "oceania"],
  ["PY", "Paraguay", "south-america"],
  ["QA", "Qatar", "asia"],
  ["RE", "Réunion", "africa"],
  ["RO", "Romania", "europe"],
  ["RS", "Serbia", "europe"],
  ["RU", "Russian Federation", "europe"],
  ["RW", "Rwanda", "africa"],
  ["SA", "Saudi Arabia", "asia"],
  ["SB", "Solomon Islands", "oceania"],
  ["SC", "Seychelles", "africa"],
  ["SD", "Sudan", "africa"],
  ["SE", "Sweden", "europe"],
  ["SG", "Singapore", "asia"],
  ["SH", "Saint Helena, Ascension and Tristan da Cunha", "africa"],
  ["SI", "Slovenia", "europe"],
  ["SJ", "Svalbard and Jan Mayen", "europe"],
  ["SK", "Slovakia", "europe"],
  ["SL", "Sierra Leone", "africa"],
  ["SM", "San Marino", "europe"],
  ["SN", "Senegal", "africa"],
  ["SO", "Somalia", "africa"],
  ["SR", "Suriname", "south-america"],
  ["SS", "South Sudan", "africa"],
  ["ST", "Sao Tome and Principe", "africa"],
  ["SV", "El Salvador", "north-america"],
  ["SX", "Sint Maarten (Dutch part)", "caribbean"],
  ["SY", "Syrian Arab Republic", "asia"],
  ["SZ", "Eswatini", "africa"],
  ["TC", "Turks and Caicos Islands", "caribbean"],
  ["TD", "Chad", "africa"],
  ["TF", "French Southern Territories", "antarctica"],
  ["TG", "Togo", "africa"],
  ["TH", "Thailand", "asia"],
  ["TJ", "Tajikistan", "asia"],
  ["TK", "Tokelau", "oceania"],
  ["TL", "Timor-Leste", "asia"],
  ["TM", "Turkmenistan", "asia"],
  ["TN", "Tunisia", "africa"],
  ["TO", "Tonga", "oceania"],
  ["TR", "Turkey", "asia"],
  ["TT", "Trinidad and Tobago", "caribbean"],
  ["TV", "Tuvalu", "oceania"],
  ["TW", "Taiwan, Province of China", "asia"],
  ["TZ", "Tanzania, United Republic of", "africa"],
  ["UA", "Ukraine", "europe"],
  ["UG", "Uganda", "africa"],
  ["UM", "United States Minor Outlying Islands", "oceania"],
  ["US", "United States", "north-america"],
  ["UY", "Uruguay", "south-america"],
  ["UZ", "Uzbekistan", "asia"],
  ["VA", "Holy See", "europe"],
  ["VC", "Saint Vincent and the Grenadines", "caribbean"],
  ["VE", "Venezuela, Bolivarian Republic of", "south-america"],
  ["VG", "Virgin Islands, British", "caribbean"],
  ["VI", "Virgin Islands, U.S.", "caribbean"],
  ["VN", "Viet Nam", "asia"],
  ["VU", "Vanuatu", "oceania"],
  ["WF", "Wallis and Futuna", "oceania"],
  ["WS", "Samoa", "oceania"],
  ["YE", "Yemen", "asia"],
  ["YT", "Mayotte", "africa"],
  ["ZA", "South Africa", "africa"],
  ["ZM", "Zambia", "africa"],
  ["ZW", "Zimbabwe", "africa"],
]);

const COUNTRY_BY_SLUG = new Map(
  COUNTRIES.map(([code, name, continent]) => [toDestinationSlug(name), { code, name, continent }])
);

export const continentName = (continentSlug) => CONTINENTS[continentSlug] || "";

export const findCountryByName = (name) => COUNTRY_BY_SLUG.get(toDestinationSlug(name)) || null;

export const listCountries = () => COUNTRIES.map(([code, name, continent]) => ({ code, name, continent }));
