/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from 'react'
import {getOverrideProps} from './utils'
import {Flex, Icon, Text, View} from '@aws-amplify/ui-react'
export default function Property1Opened(props) {
  const {overrides, ...rest} = props
  return (
    <Flex
      gap="18px"
      direction="row"
      width="unset"
      height="unset"
      justifyContent="flex-start"
      alignItems="flex-start"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, 'Property1Opened')}
      {...rest}>
      <Flex
        gap="18px"
        direction="row"
        width="unset"
        height="unset"
        justifyContent="flex-start"
        alignItems="center"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, 'Frame 199')}>
        <Text
          fontFamily="Ubuntu"
          fontSize="16px"
          fontWeight="500"
          color="rgba(55,65,81,1)"
          lineHeight="20px"
          textAlign="right"
          display="block"
          direction="column"
          justifyContent="unset"
          letterSpacing="-0.01px"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Starting date"
          {...getOverrideProps(overrides, 'Field label')}></Text>
        <Flex
          gap="16px"
          direction="column"
          width="unset"
          height="unset"
          justifyContent="center"
          alignItems="center"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, 'Frame 13')}>
          <Flex
            gap="6px"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="center"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'Frame 3124388')}>
            <Flex
              gap="0"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="flex-start"
              alignItems="center"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Frame 3124389')}>
              <Flex
                gap="0"
                direction="row"
                width="300px"
                height="unset"
                justifyContent="flex-start"
                alignItems="center"
                overflow="hidden"
                shrink="0"
                position="relative"
                border="1px SOLID rgba(17,106,204,1)"
                borderRadius="7px"
                padding="7px 15px 7px 15px"
                backgroundColor="rgba(160,195,255,0.1)"
                {...getOverrideProps(overrides, 'Frame 2')}>
                <Text
                  fontFamily="Ubuntu"
                  fontSize="16px"
                  fontWeight="500"
                  color="rgba(55,65,81,1)"
                  lineHeight="20px"
                  textAlign="left"
                  display="block"
                  direction="column"
                  justifyContent="unset"
                  letterSpacing="-0.01px"
                  width="244px"
                  height="28px"
                  gap="unset"
                  alignItems="unset"
                  shrink="0"
                  position="relative"
                  padding="0px 0px 0px 0px"
                  whiteSpace="pre-wrap"
                  children="|"
                  {...getOverrideProps(overrides, 'Field text')}></Text>
                <View
                  width="24px"
                  height="24px"
                  {...getOverrideProps(overrides, 'basic / calendar')}></View>
              </Flex>
            </Flex>
          </Flex>
        </Flex>
      </Flex>
      <Flex
        gap="0"
        direction="column"
        width="344px"
        height="unset"
        justifyContent="flex-start"
        alignItems="flex-start"
        shrink="0"
        position="relative"
        boxShadow="0px 30px 84px rgba(0.07450979948043823, 0.039215683937072754, 0.18039216101169586, 0.07999999821186066)"
        borderRadius="12px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(24,34,51,1)"
        {...getOverrideProps(overrides, 'Calendar')}>
        <Flex
          gap="0"
          direction="column"
          width="unset"
          height="unset"
          justifyContent="flex-start"
          alignItems="center"
          shrink="0"
          alignSelf="stretch"
          position="relative"
          padding="16px 32px 16px 32px"
          {...getOverrideProps(overrides, 'Calendar ')}>
          <Flex
            gap="0"
            direction="row"
            width="344px"
            height="unset"
            justifyContent="center"
            alignItems="flex-start"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'header')}>
            <Flex
              gap="0"
              direction="row"
              width="22px"
              height="30px"
              justifyContent="flex-start"
              alignItems="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 40px 0px"
              {...getOverrideProps(overrides, 'Frame 203')}>
              <Icon
                width="16px"
                height="16px"
                viewBox={{
                  minX: 0,
                  minY: 0,
                  width: 22.627416610717773,
                  height: 22.627416610717773,
                }}
                paths={[
                  {
                    d: 'M0.28547 2.42892C0.13792 1.17349 1.17752 0.0977479 2.43725 0.202321L14.364 1.19238L16 16L1.63605 13.9203L0.28547 2.42892Z',
                    fill: 'rgba(24,34,51,1)',
                    fillRule: 'nonzero',
                  },
                ]}
                display="block"
                gap="unset"
                alignItems="unset"
                justifyContent="unset"
                shrink="0"
                position="relative"
                {...getOverrideProps(overrides, 'Shape-beak')}></Icon>
            </Flex>
            <Flex
              gap="0"
              direction="row"
              width="344px"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Frame 229')}>
              <Flex
                gap="8px"
                direction="row"
                width="unset"
                height="unset"
                justifyContent="center"
                alignItems="center"
                shrink="0"
                position="relative"
                borderRadius="8px"
                padding="8px 8px 8px 16px"
                {...getOverrideProps(overrides, 'Select124399')}>
                <Flex
                  gap="0"
                  direction="row"
                  width="unset"
                  height="unset"
                  justifyContent="flex-start"
                  alignItems="center"
                  shrink="0"
                  position="relative"
                  padding="0px 0px 0px 0px"
                  {...getOverrideProps(overrides, 'text124400')}>
                  <Text
                    fontFamily="Ubuntu"
                    fontSize="14px"
                    fontWeight="500"
                    color="rgba(243,244,246,1)"
                    lineHeight="20px"
                    textAlign="left"
                    display="block"
                    direction="column"
                    justifyContent="unset"
                    letterSpacing="0px"
                    width="unset"
                    height="unset"
                    gap="unset"
                    alignItems="unset"
                    shrink="0"
                    position="relative"
                    padding="0px 0px 0px 0px"
                    whiteSpace="pre-wrap"
                    children="April"
                    {...getOverrideProps(overrides, 'April')}></Text>
                  <View
                    width="24px"
                    height="24px"
                    display="block"
                    gap="unset"
                    alignItems="unset"
                    justifyContent="unset"
                    overflow="hidden"
                    shrink="0"
                    position="relative"
                    padding="0px 0px 0px 0px"
                    {...getOverrideProps(overrides, 'Chevron Down124402')}>
                    <Icon
                      width="8.5px"
                      height="4.5px"
                      viewBox={{minX: 0, minY: 0, width: 8.5, height: 4.5}}
                      paths={[
                        {
                          d: 'M0.54526 -0.514968C0.260851 -0.816106 -0.213829 -0.829669 -0.514968 -0.54526C-0.816106 -0.260851 -0.829669 0.213829 -0.54526 0.514968L0.54526 -0.514968ZM4.25 4.5L3.70474 5.01497C3.84642 5.16498 4.04365 5.25 4.25 5.25C4.45635 5.25 4.65358 5.16498 4.79526 5.01497L4.25 4.5ZM9.04526 0.514968C9.32967 0.213829 9.31611 -0.260851 9.01497 -0.54526C8.71383 -0.829669 8.23915 -0.816106 7.95474 -0.514968L9.04526 0.514968ZM-0.54526 0.514968L3.70474 5.01497L4.79526 3.98503L0.54526 -0.514968L-0.54526 0.514968ZM4.79526 5.01497L9.04526 0.514968L7.95474 -0.514968L3.70474 3.98503L4.79526 5.01497Z',
                          stroke: 'rgba(243,244,246,1)',
                          fillRule: 'nonzero',
                          strokeLinejoin: 'round',
                          strokeWidth: 1,
                        },
                      ]}
                      display="block"
                      gap="unset"
                      alignItems="unset"
                      justifyContent="unset"
                      position="absolute"
                      top="40.63%"
                      bottom="40.63%"
                      left="32.29%"
                      right="32.29%"
                      {...getOverrideProps(overrides, 'Vector124403')}></Icon>
                  </View>
                </Flex>
              </Flex>
              <Flex
                gap="8px"
                direction="row"
                width="unset"
                height="unset"
                justifyContent="center"
                alignItems="center"
                shrink="0"
                position="relative"
                borderRadius="8px"
                padding="8px 8px 8px 16px"
                {...getOverrideProps(overrides, 'Select124404')}>
                <Flex
                  gap="0"
                  direction="row"
                  width="unset"
                  height="unset"
                  justifyContent="flex-start"
                  alignItems="center"
                  shrink="0"
                  position="relative"
                  padding="0px 0px 0px 0px"
                  {...getOverrideProps(overrides, 'text124405')}>
                  <Text
                    fontFamily="Ubuntu"
                    fontSize="14px"
                    fontWeight="500"
                    color="rgba(243,244,246,1)"
                    lineHeight="20px"
                    textAlign="left"
                    display="block"
                    direction="column"
                    justifyContent="unset"
                    letterSpacing="0px"
                    width="unset"
                    height="unset"
                    gap="unset"
                    alignItems="unset"
                    shrink="0"
                    position="relative"
                    padding="0px 0px 0px 0px"
                    whiteSpace="pre-wrap"
                    children="2021"
                    {...getOverrideProps(overrides, '2021')}></Text>
                  <View
                    width="24px"
                    height="24px"
                    display="block"
                    gap="unset"
                    alignItems="unset"
                    justifyContent="unset"
                    overflow="hidden"
                    shrink="0"
                    position="relative"
                    padding="0px 0px 0px 0px"
                    {...getOverrideProps(overrides, 'Chevron Down124407')}>
                    <Icon
                      width="8.5px"
                      height="4.5px"
                      viewBox={{minX: 0, minY: 0, width: 8.5, height: 4.5}}
                      paths={[
                        {
                          d: 'M0.54526 -0.514968C0.260851 -0.816106 -0.213829 -0.829669 -0.514968 -0.54526C-0.816106 -0.260851 -0.829669 0.213829 -0.54526 0.514968L0.54526 -0.514968ZM4.25 4.5L3.70474 5.01497C3.84642 5.16498 4.04365 5.25 4.25 5.25C4.45635 5.25 4.65358 5.16498 4.79526 5.01497L4.25 4.5ZM9.04526 0.514968C9.32967 0.213829 9.31611 -0.260851 9.01497 -0.54526C8.71383 -0.829669 8.23915 -0.816106 7.95474 -0.514968L9.04526 0.514968ZM-0.54526 0.514968L3.70474 5.01497L4.79526 3.98503L0.54526 -0.514968L-0.54526 0.514968ZM4.79526 5.01497L9.04526 0.514968L7.95474 -0.514968L3.70474 3.98503L4.79526 5.01497Z',
                          stroke: 'rgba(255,255,255,1)',
                          fillRule: 'nonzero',
                          strokeLinejoin: 'round',
                          strokeWidth: 1,
                        },
                      ]}
                      display="block"
                      gap="unset"
                      alignItems="unset"
                      justifyContent="unset"
                      position="absolute"
                      top="40.63%"
                      bottom="40.63%"
                      left="32.29%"
                      right="32.29%"
                      {...getOverrideProps(overrides, 'Vector124408')}></Icon>
                  </View>
                </Flex>
              </Flex>
            </Flex>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="40px"
            justifyContent="center"
            alignItems="flex-start"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'row124409')}>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124410')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="13px"
                fontWeight="500"
                color="rgba(243,244,246,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Mo"
                {...getOverrideProps(overrides, 'Mo')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124412')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="13px"
                fontWeight="500"
                color="rgba(243,244,246,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Tu"
                {...getOverrideProps(overrides, 'Tu')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124414')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="13px"
                fontWeight="500"
                color="rgba(243,244,246,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="We"
                {...getOverrideProps(overrides, 'We')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124416')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="13px"
                fontWeight="500"
                color="rgba(243,244,246,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Th"
                {...getOverrideProps(overrides, 'Th')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124418')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="13px"
                fontWeight="500"
                color="rgba(243,244,246,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Fri"
                {...getOverrideProps(overrides, 'Fri')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124420')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="13px"
                fontWeight="500"
                color="rgba(243,244,246,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Sa"
                {...getOverrideProps(overrides, 'Sa')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124422')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="13px"
                fontWeight="500"
                color="rgba(243,244,246,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Su"
                {...getOverrideProps(overrides, 'Su')}></Text>
            </View>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="40px"
            justifyContent="flex-start"
            alignItems="center"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'row124424')}>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124425')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 8px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="29"
                {...getOverrideProps(overrides, '29124426')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124427')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="30"
                {...getOverrideProps(overrides, '30124428')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124429')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="31"
                {...getOverrideProps(overrides, '31')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124431')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="1"
                {...getOverrideProps(overrides, '1124432')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              backgroundColor="rgba(243,244,246,0.5)"
              {...getOverrideProps(overrides, 'Cells124433')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="2"
                {...getOverrideProps(overrides, '2124434')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124436')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="3"
                {...getOverrideProps(overrides, '3124437')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124438')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="4"
                {...getOverrideProps(overrides, '4124439')}></Text>
            </View>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="40px"
            justifyContent="flex-start"
            alignItems="center"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'row124440')}>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124441')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="5"
                {...getOverrideProps(overrides, '5124442')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124443')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="6"
                {...getOverrideProps(overrides, '6124444')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124445')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="7"
                {...getOverrideProps(overrides, '7124446')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124447')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="8"
                {...getOverrideProps(overrides, '8124448')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124449')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="9"
                {...getOverrideProps(overrides, '9124450')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124451')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="10"
                {...getOverrideProps(overrides, '10')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124453')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="11"
                {...getOverrideProps(overrides, '11')}></Text>
            </View>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="40px"
            justifyContent="flex-start"
            alignItems="center"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'row124455')}>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124456')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="12"
                {...getOverrideProps(overrides, '12')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124458')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="13"
                {...getOverrideProps(overrides, '13')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124460')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="14"
                {...getOverrideProps(overrides, '14')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124462')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="15"
                {...getOverrideProps(overrides, '15')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124464')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="16"
                {...getOverrideProps(overrides, '16')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124466')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="17"
                {...getOverrideProps(overrides, '17')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124468')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="18"
                {...getOverrideProps(overrides, '18')}></Text>
            </View>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="40px"
            justifyContent="flex-start"
            alignItems="center"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'row124470')}>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124471')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="19"
                {...getOverrideProps(overrides, '19')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124473')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="20"
                {...getOverrideProps(overrides, '20')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124475')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="21"
                {...getOverrideProps(overrides, '21')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124477')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="22"
                {...getOverrideProps(overrides, '22')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124479')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="23"
                {...getOverrideProps(overrides, '23')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124481')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="24"
                {...getOverrideProps(overrides, '24')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124483')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="25"
                {...getOverrideProps(overrides, '25')}></Text>
            </View>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="40px"
            justifyContent="flex-start"
            alignItems="center"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'row124485')}>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124486')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="26"
                {...getOverrideProps(overrides, '26')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              backgroundColor="rgba(17,106,204,1)"
              {...getOverrideProps(overrides, 'Cells124488')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 0px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="27"
                {...getOverrideProps(overrides, '27')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124490')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="28"
                {...getOverrideProps(overrides, '28')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124492')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="29"
                {...getOverrideProps(overrides, '29124493')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(overrides, 'Cells124494')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="30"
                {...getOverrideProps(overrides, '30124495')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124496')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="1"
                {...getOverrideProps(overrides, '1124497')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124498')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="2"
                {...getOverrideProps(overrides, '2124499')}></Text>
            </View>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="40px"
            justifyContent="flex-start"
            alignItems="center"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, 'row124500')}>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124501')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="3"
                {...getOverrideProps(overrides, '3124502')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124503')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="4"
                {...getOverrideProps(overrides, '4124504')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124505')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="5"
                {...getOverrideProps(overrides, '5124506')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124507')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="6"
                {...getOverrideProps(overrides, '6124508')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124509')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="7"
                {...getOverrideProps(overrides, '7124510')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124511')}>
              <Text
                fontFamily="Ubuntu"
                fontSize="14px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="20px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 10px - 2px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="8"
                {...getOverrideProps(overrides, '8124512')}></Text>
            </View>
            <View
              width="unset"
              height="unset"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              borderRadius="40px"
              padding="0px 0px 0px 0px"
              opacity="0.4000000059604645"
              {...getOverrideProps(overrides, 'Cells124513')}>
              <Text
                fontFamily="Kanit"
                fontSize="13px"
                fontWeight="500"
                color="rgba(209,213,219,1)"
                lineHeight="19px"
                textAlign="center"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="0px"
                width="24px"
                height="unset"
                gap="unset"
                alignItems="unset"
                position="absolute"
                top="calc(50% - 9.5px - 2.5px)"
                left="calc(50% - 12px - 0px)"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="9"
                {...getOverrideProps(overrides, '9124514')}></Text>
            </View>
          </Flex>
        </Flex>
        <Flex
          gap="8px"
          direction="row"
          width="unset"
          height="unset"
          justifyContent="flex-start"
          alignItems="center"
          shrink="0"
          alignSelf="stretch"
          position="relative"
          padding="0px 32px 16px 32px"
          {...getOverrideProps(overrides, 'Confirmation')}>
          <Flex
            gap="8px"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="center"
            alignItems="center"
            grow="1"
            shrink="1"
            basis="0"
            position="relative"
            borderRadius="8px"
            padding="8px 16px 8px 16px"
            backgroundColor="rgba(243,244,246,1)"
            {...getOverrideProps(overrides, 'Button124516')}>
            <Text
              fontFamily="Ubuntu"
              fontSize="14px"
              fontWeight="500"
              color="rgba(24,34,51,1)"
              lineHeight="20px"
              textAlign="center"
              display="block"
              direction="column"
              justifyContent="unset"
              letterSpacing="0px"
              width="48px"
              height="24px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Cancel"
              {...getOverrideProps(overrides, 'Cancel')}></Text>
          </Flex>
          <Flex
            gap="8px"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="center"
            alignItems="center"
            grow="1"
            shrink="1"
            basis="0"
            position="relative"
            borderRadius="8px"
            padding="8px 105px 8px 105px"
            backgroundColor="rgba(17,106,204,1)"
            {...getOverrideProps(overrides, 'Button124518')}>
            <Text
              fontFamily="Ubuntu"
              fontSize="14px"
              fontWeight="500"
              color="rgba(255,255,255,1)"
              lineHeight="20px"
              textAlign="center"
              display="block"
              direction="column"
              justifyContent="unset"
              letterSpacing="0px"
              width="64px"
              height="24px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Set Date"
              {...getOverrideProps(overrides, 'Set Date')}></Text>
          </Flex>
        </Flex>
      </Flex>
    </Flex>
  )
}
