const hostReservationDetailsContent = {
  en: {
    pageTitle: "Reservation details",
    states: {
      failedToLoad: "Failed to load reservation.",
      noReservationFound: "No reservation found.",
    },
    buttons: {
      back: "Back to reservations",
      messageGuest: "Message guest",
      viewInCalendar: "View in calendar",
      downloadReceipt: "Download receipt",
      preparingReceipt: "Preparing receipt...",
    },
    headings: {
      property: "Property",
      guest: "Guest",
      payment: "Payment",
      reservationInfo: "Reservation Info",
      actions: "Actions",
      checkInInstructions: "Check-in instructions",
      houseRules: "House Rules",
      cancellationPolicy: "Cancellation Policy",
      specialRequest: "Special request",
    },
    labels: {
      bookedVia: "Booked via",
      checkIn: "Check-in",
      bookedOn: "Booked on",
      reservationId: "Reservation ID",
      confirmation: "Confirmation",
      cleaningFee: "Cleaning fee",
      totalPaid: "Total paid",
      method: "Method",
      propertyImageAlt: "Property image",
      guestFallbackName: "Guest",
      loadingValue: "Loading...",
      unavailable: "unavailable",
      none: "None",
      locationUnavailable: "Location unavailable",
      loadingLocation: "Loading location...",
      night: "night",
      nights: "nights",
      guest: "guest",
      guests: "guests",
    },
    loading: {
      status: "Loading",
      summary: "Loading reservation summary...",
      reservationDetails: "Loading reservation details...",
      guestEmail: "Loading guest email...",
      guestPhone: "Loading guest phone...",
      checkInInstructions: "Loading check-in instructions...",
      houseRules: "Loading house rules...",
      cancellationPolicy: "Loading cancellation policy...",
      payment: "Loading payment",
      paymentStatus: "Loading payment status",
    },
    empty: {
      noCheckInInstructions: "No check-in instructions",
      noHouseRulesSpecified: "No house rules specified",
      noCancellationPolicySelected: "No cancellation policy selected.",
      paymentStatusUnavailable: "Payment status unavailable",
      reservation: "Reservation",
    },
    status: {
      PAID: "Confirmed",
      AWAITING_PAYMENT: "Awaiting payment",
      FAILED: "Failed",
      DECLINED: "Declined",
      INQUIRY: "Request",
    },
    paymentStatus: {
      PAID: {
        label: "Payment received",
        text: "Paid in full on",
      },
      AWAITING_PAYMENT: {
        label: "Awaiting payment",
        text: "Payment pending",
      },
      FAILED: {
        label: "Payment failed",
        text: "Payment was not successful",
      },
      DECLINED: {
        label: "Payment declined",
        text: "Payment was declined",
      },
      INQUIRY: {
        label: "Pending request",
        text: "Waiting for host review",
      },
    },
  },
  nl: {
    pageTitle: "Reserveringsdetails",
    states: {
      failedToLoad: "Reservering laden mislukt.",
      noReservationFound: "Geen reservering gevonden.",
    },
    buttons: {
      back: "Terug naar reserveringen",
      messageGuest: "Stuur bericht",
      viewInCalendar: "Bekijk in kalender",
      downloadReceipt: "Download bon",
      preparingReceipt: "Bon voorbereiden...",
    },
    headings: {
      property: "Accommodatie",
      guest: "Gast",
      payment: "Betaling",
      reservationInfo: "Reserveringsinfo",
      actions: "Acties",
      checkInInstructions: "Check-in instructies",
      houseRules: "Huisregels",
      cancellationPolicy: "Annuleringsbeleid",
      specialRequest: "Speciaal verzoek",
    },
    labels: {
      bookedVia: "Geboekt via",
      checkIn: "Check-in",
      bookedOn: "Geboekt op",
      reservationId: "Reserverings-ID",
      confirmation: "Bevestiging",
      cleaningFee: "Schoonmaakkosten",
      totalPaid: "Totaal betaald",
      method: "Methode",
      propertyImageAlt: "Afbeelding van accommodatie",
      guestFallbackName: "Gast",
      loadingValue: "Laden...",
      unavailable: "onbeschikbaar",
      none: "Geen",
      locationUnavailable: "Locatie onbeschikbaar",
      loadingLocation: "Locatie laden...",
      night: "nacht",
      nights: "nachten",
      guest: "gast",
      guests: "gasten",
    },
    loading: {
      status: "Laden",
      summary: "Reserveringsoverzicht laden...",
      reservationDetails: "Reserveringsdetails laden...",
      guestEmail: "E-mailadres van gast laden...",
      guestPhone: "Telefoonnummer van gast laden...",
      checkInInstructions: "Check-in instructies laden...",
      houseRules: "Huisregels laden...",
      cancellationPolicy: "Annuleringsbeleid laden...",
      payment: "Betaling laden",
      paymentStatus: "Betaalstatus laden",
    },
    empty: {
      noCheckInInstructions: "Geen check-in instructies",
      noHouseRulesSpecified: "Geen huisregels opgegeven",
      noCancellationPolicySelected: "Geen annuleringsbeleid geselecteerd.",
      paymentStatusUnavailable: "Betaalstatus onbeschikbaar",
      reservation: "Reservering",
    },
    status: {
      PAID: "Bevestigd",
      AWAITING_PAYMENT: "Wacht op betaling",
      FAILED: "Mislukt",
      DECLINED: "Geweigerd",
      INQUIRY: "Aanvraag",
    },
    paymentStatus: {
      PAID: {
        label: "Betaling ontvangen",
        text: "Volledig betaald op",
      },
      AWAITING_PAYMENT: {
        label: "Wacht op betaling",
        text: "Betaling in afwachting",
      },
      FAILED: {
        label: "Betaling mislukt",
        text: "Betaling was niet succesvol",
      },
      DECLINED: {
        label: "Betaling geweigerd",
        text: "Betaling is geweigerd",
      },
      INQUIRY: {
        label: "Aanvraag in behandeling",
        text: "Wacht op beoordeling van host",
      },
    },
  },
  de: {
    pageTitle: "Reservierungsdetails",
    states: {
      failedToLoad: "Reservierung konnte nicht geladen werden.",
      noReservationFound: "Keine Reservierung gefunden.",
    },
    buttons: {
      back: "Zuruck zu Reservierungen",
      messageGuest: "Gast anschreiben",
      viewInCalendar: "Im Kalender ansehen",
      downloadReceipt: "Beleg herunterladen",
      preparingReceipt: "Beleg wird vorbereitet...",
    },
    headings: {
      property: "Unterkunft",
      guest: "Gast",
      payment: "Zahlung",
      reservationInfo: "Reservierungsinfo",
      actions: "Aktionen",
      checkInInstructions: "Check-in Hinweise",
      houseRules: "Hausregeln",
      cancellationPolicy: "Stornierungsrichtlinie",
      specialRequest: "Besonderer Wunsch",
    },
    labels: {
      bookedVia: "Gebucht uber",
      checkIn: "Check-in",
      bookedOn: "Gebucht am",
      reservationId: "Reservierungs-ID",
      confirmation: "Bestatigung",
      cleaningFee: "Reinigungsgebuhr",
      totalPaid: "Insgesamt bezahlt",
      method: "Methode",
      propertyImageAlt: "Unterkunftsbild",
      guestFallbackName: "Gast",
      loadingValue: "Wird geladen...",
      unavailable: "nicht verfugbar",
      none: "Keine",
      locationUnavailable: "Standort nicht verfugbar",
      loadingLocation: "Standort wird geladen...",
      night: "Nacht",
      nights: "Nachte",
      guest: "Gast",
      guests: "Gaste",
    },
    loading: {
      status: "Wird geladen",
      summary: "Reservierungsubersicht wird geladen...",
      reservationDetails: "Reservierungsdetails werden geladen...",
      guestEmail: "E-Mail des Gasts wird geladen...",
      guestPhone: "Telefonnummer des Gasts wird geladen...",
      checkInInstructions: "Check-in Hinweise werden geladen...",
      houseRules: "Hausregeln werden geladen...",
      cancellationPolicy: "Stornierungsrichtlinie wird geladen...",
      payment: "Zahlung wird geladen",
      paymentStatus: "Zahlungsstatus wird geladen",
    },
    empty: {
      noCheckInInstructions: "Keine Check-in Hinweise",
      noHouseRulesSpecified: "Keine Hausregeln angegeben",
      noCancellationPolicySelected: "Keine Stornierungsrichtlinie ausgewahlt.",
      paymentStatusUnavailable: "Zahlungsstatus nicht verfugbar",
      reservation: "Reservierung",
    },
    status: {
      PAID: "Bestatigt",
      AWAITING_PAYMENT: "Wartet auf Zahlung",
      FAILED: "Fehlgeschlagen",
      DECLINED: "Abgelehnt",
      INQUIRY: "Anfrage",
    },
    paymentStatus: {
      PAID: {
        label: "Zahlung erhalten",
        text: "Vollstandig bezahlt am",
      },
      AWAITING_PAYMENT: {
        label: "Wartet auf Zahlung",
        text: "Zahlung ausstehend",
      },
      FAILED: {
        label: "Zahlung fehlgeschlagen",
        text: "Zahlung war nicht erfolgreich",
      },
      DECLINED: {
        label: "Zahlung abgelehnt",
        text: "Zahlung wurde abgelehnt",
      },
      INQUIRY: {
        label: "Anfrage ausstehend",
        text: "Wartet auf Prufung durch den Host",
      },
    },
  },
  es: {
    pageTitle: "Detalles de la reserva",
    states: {
      failedToLoad: "No se pudo cargar la reserva.",
      noReservationFound: "No se encontro ninguna reserva.",
    },
    buttons: {
      back: "Volver a reservas",
      messageGuest: "Enviar mensaje",
      viewInCalendar: "Ver en calendario",
      downloadReceipt: "Descargar recibo",
      preparingReceipt: "Preparando recibo...",
    },
    headings: {
      property: "Alojamiento",
      guest: "Huesped",
      payment: "Pago",
      reservationInfo: "Informacion de la reserva",
      actions: "Acciones",
      checkInInstructions: "Instrucciones de check-in",
      houseRules: "Normas de la casa",
      cancellationPolicy: "Politica de cancelacion",
      specialRequest: "Solicitud especial",
    },
    labels: {
      bookedVia: "Reservado mediante",
      checkIn: "Check-in",
      bookedOn: "Reservado el",
      reservationId: "ID de reserva",
      confirmation: "Confirmacion",
      cleaningFee: "Tarifa de limpieza",
      totalPaid: "Total pagado",
      method: "Metodo",
      propertyImageAlt: "Imagen del alojamiento",
      guestFallbackName: "Huesped",
      loadingValue: "Cargando...",
      unavailable: "no disponible",
      none: "Ninguno",
      locationUnavailable: "Ubicacion no disponible",
      loadingLocation: "Cargando ubicacion...",
      night: "noche",
      nights: "noches",
      guest: "huesped",
      guests: "huespedes",
    },
    loading: {
      status: "Cargando",
      summary: "Cargando resumen de la reserva...",
      reservationDetails: "Cargando detalles de la reserva...",
      guestEmail: "Cargando correo del huesped...",
      guestPhone: "Cargando telefono del huesped...",
      checkInInstructions: "Cargando instrucciones de check-in...",
      houseRules: "Cargando normas de la casa...",
      cancellationPolicy: "Cargando politica de cancelacion...",
      payment: "Cargando pago",
      paymentStatus: "Cargando estado del pago",
    },
    empty: {
      noCheckInInstructions: "No hay instrucciones de check-in",
      noHouseRulesSpecified: "No se especificaron normas de la casa",
      noCancellationPolicySelected: "No se selecciono ninguna politica de cancelacion.",
      paymentStatusUnavailable: "Estado del pago no disponible",
      reservation: "Reserva",
    },
    status: {
      PAID: "Confirmada",
      AWAITING_PAYMENT: "Pago pendiente",
      FAILED: "Fallida",
      DECLINED: "Rechazada",
      INQUIRY: "Solicitud",
    },
    paymentStatus: {
      PAID: {
        label: "Pago recibido",
        text: "Pagado por completo el",
      },
      AWAITING_PAYMENT: {
        label: "Pago pendiente",
        text: "Pago pendiente",
      },
      FAILED: {
        label: "Pago fallido",
        text: "El pago no fue exitoso",
      },
      DECLINED: {
        label: "Pago rechazado",
        text: "El pago fue rechazado",
      },
      INQUIRY: {
        label: "Solicitud pendiente",
        text: "Esperando revision del anfitrion",
      },
    },
  },
};

export default hostReservationDetailsContent;
