export const vatRates = [
  {country: 'Afghanistan', vat: '0'},
  {country: 'Albania', vat: '20'},
  {country: 'Algeria', vat: '19'},
  {country: 'American Samoa', vat: '0'},
  {country: 'Andorra', vat: '4.5'},
  {country: 'Angola', vat: '14'},
  {country: 'Anguilla', vat: '0'},
  {country: 'Antarctica', vat: '0'},
  {country: 'Antigua and Barbuda', vat: '15'},
  {country: 'Argentina', vat: '21'},
  {country: 'Armenia', vat: '20'},
  {country: 'Aruba', vat: '6'},
  {country: 'Australia', vat: '10'},
  {country: 'Austria', vat: '20'},
  {country: 'Azerbaijan', vat: '18'},
  {country: 'Bahamas', vat: '10'},
  {country: 'Bahrain', vat: '10'},
  {country: 'Bangladesh', vat: '15'},
  {country: 'Barbados', vat: '17.5'},
  {country: 'Belarus', vat: '20'},
  {country: 'Belgium', vat: '21'},
  {country: 'Belize', vat: '12.5'},
  {country: 'Benin', vat: '18'},
  {country: 'Bermuda', vat: '0'},
  {country: 'Bhutan', vat: '0'},
  {country: 'Bolivia', vat: '13'},
  {country: 'Bonaire, Sint Eustatius, and Saba', vat: '0'},
  {country: 'Bosnia and Herzegovina', vat: '17'},
  {country: 'Botswana', vat: '14'},
  {country: 'Brazil', vat: '25'}, // 17 - 25
  {country: 'British Indian Ocean Territory', vat: '0'},
  {country: 'Brunei Darussalam', vat: '0'},
  {country: 'Bulgaria', vat: '20'},
  {country: 'Burkina Faso', vat: '18'},
  {country: 'Burundi', vat: '18'},
  {country: 'Cabo Verde', vat: '15'},
  {country: 'Cambodia', vat: '10'},
  {country: 'Cameroon', vat: '19.25'},
  {country: 'Canada', vat: '5'},
  {country: 'Cayman Islands', vat: '0'},
  {country: 'Central African Republic', vat: '19'},
  {country: 'Chad', vat: '18'},
  {country: 'Chile', vat: '19'},
  {country: 'China', vat: '13'},
  {country: 'Colombia', vat: '19'},
  {country: 'Comoros', vat: '10'},
  {country: 'Congo', vat: '18'},
  {country: 'Congo (Democratic Republic)', vat: '16'},
  {country: 'Costa Rica', vat: '13'},
  {country: "Côte d'Ivoire", vat: '18'},
  {country: 'Croatia', vat: '25'},
  {country: 'Cuba', vat: '4'},
  {country: 'Cyprus', vat: '19'},
  {country: 'Czech Republic', vat: '21'},
  {country: 'Denmark', vat: '25'},
  {country: 'Djibouti', vat: '10'},
  {country: 'Dominica', vat: '15'},
  {country: 'Dominican Republic', vat: '18'},
  {country: 'Ecuador', vat: '12'},
  {country: 'Egypt', vat: '14'},
  {country: 'El Salvador', vat: '13'},
  {country: 'Equatorial Guinea', vat: '15'},
  {country: 'Eritrea', vat: '0'},
  {country: 'Estonia', vat: '22'}, // (24 starting July 2025)
  {country: 'Eswatini', vat: '15'},
  {country: 'Ethiopia', vat: '15'},
  {country: 'Fiji', vat: '15'},
  {country: 'Finland', vat: '25.5'},
  {country: 'France', vat: '20'},
  {country: 'Gabon', vat: '18'},
  {country: 'Gambia', vat: '15'},
  {country: 'Georgia', vat: '18'},
  {country: 'Germany', vat: '19'},
  {country: 'Ghana', vat: '15'},
  {country: 'Greece', vat: '24'},
  {country: 'Grenada', vat: '15'},
  {country: 'Guatemala', vat: '12'},
  {country: 'Guinea', vat: '18'},
  {country: 'Guinea-Bissau', vat: '15'},
  {country: 'Guyana', vat: '14'},
  {country: 'Haiti', vat: '10'},
  {country: 'Honduras', vat: '15'},
  {country: 'Hong Kong', vat: '0'},
  {country: 'Hungary', vat: '27'},
  {country: 'Iceland', vat: '24'},
  {country: 'India', vat: '28'}, // Varies (5, 12, 18, 28)
  {country: 'Indonesia', vat: '11'},
  {country: 'Iran', vat: '9'},
  {country: 'Iraq', vat: '15'},
  {country: 'Ireland', vat: '23'},
  {country: 'Israel', vat: '17'},
  {country: 'Italy', vat: '22'},
  {country: 'Jamaica', vat: '15'},
  {country: 'Japan', vat: '10'},
  {country: 'Jordan', vat: '16'},
  {country: 'Kazakhstan', vat: '12'},
  {country: 'Kenya', vat: '16'},
  {country: 'Kiribati', vat: '0'},
  {country: 'Korea (South)', vat: '10'},
  {country: 'Kuwait', vat: '0'},
  {country: 'Kyrgyzstan', vat: '12'},
  {country: 'Laos', vat: '10'},
  {country: 'Latvia', vat: '21'},
  {country: 'Lebanon', vat: '11'},
  {country: 'Lesotho', vat: '15'},
  {country: 'Liberia', vat: '10'},
  {country: 'Libya', vat: '0'},
  {country: 'Liechtenstein', vat: '7.7'},
  {country: 'Lithuania', vat: '21'},
  {country: 'Luxembourg', vat: '17'},
  {country: 'Macau', vat: '0'},
  {country: 'Madagascar', vat: '20'},
  {country: 'Malawi', vat: '16.5'},
  {country: 'Malaysia', vat: '6'},
  {country: 'Maldives', vat: '6'},
  {country: 'Mali', vat: '18'},
  {country: 'Malta', vat: '18'},
  {country: 'Marshall Islands', vat: '0'},
  {country: 'Mauritania', vat: '16'},
  {country: 'Mauritius', vat: '15'},
  {country: 'Mexico', vat: '16'},
  {country: 'Micronesia', vat: '0'},
  {country: 'Moldova', vat: '20'},
  {country: 'Monaco', vat: '20'},
  {country: 'Mongolia', vat: '10'},
  {country: 'Montenegro', vat: '21'},
  {country: 'Morocco', vat: '20'},
  {country: 'Mozambique', vat: '17'},
  {country: 'Myanmar', vat: '5'},
  {country: 'Namibia', vat: '15'},
  {country: 'Nauru', vat: '0'},
  {country: 'Nepal', vat: '13'},
  {country: 'Netherlands', vat: '21'},
  {country: 'New Zealand', vat: '15'},
  {country: 'Nicaragua', vat: '15'},
  {country: 'Niger', vat: '19'},
  {country: 'Nigeria', vat: '7.5'},
  {country: 'North Korea', vat: '0'},
  {country: 'North Macedonia', vat: '18'},
  {country: 'Norway', vat: '25'},
  {country: 'Oman', vat: '5'},
  {country: 'Pakistan', vat: '17'},
  {country: 'Palau', vat: '0'},
  {country: 'Panama', vat: '7'},
  {country: 'Papua New Guinea', vat: '10'},
  {country: 'Paraguay', vat: '10'},
  {country: 'Peru', vat: '18'},
  {country: 'Philippines', vat: '12'},
  {country: 'Poland', vat: '23'},
  {country: 'Portugal', vat: '23'},
  {country: 'Qatar', vat: '5'},
  {country: 'Romania', vat: '19'},
  {country: 'Russia', vat: '20'},
  {country: 'Rwanda', vat: '18'},
  {country: 'Saint Kitts and Nevis', vat: '17'},
  {country: 'Saint Lucia', vat: '12.5'},
  {country: 'Saint Vincent and the Grenadines', vat: '16'},
  {country: 'Samoa', vat: '15'},
  {country: 'San Marino', vat: '17'},
  {country: 'Sao Tome and Principe', vat: '15'},
  {country: 'Saudi Arabia', vat: '15 (increased in 2020)'},
  {country: 'Senegal', vat: '18'},
  {country: 'Serbia', vat: '20'},
  {country: 'Seychelles', vat: '15'},
  {country: 'Sierra Leone', vat: '15'},
  {country: 'Singapore', vat: '9'}, // (increased from 8% in 2024)
  {country: 'Slovakia', vat: '20'}, // (23% starting January 2025)
  {country: 'Slovenia', vat: '22'},
  {country: 'Solomon Islands', vat: '10'},
  {country: 'Somalia', vat: '0'},
  {country: 'South Africa', vat: '15'},
  {country: 'South Korea', vat: '10'},
  {country: 'Spain', vat: '21'},
  {country: 'Sri Lanka', vat: '15'},
  {country: 'Sudan', vat: '17'},
  {country: 'Suriname', vat: '12'},
  {country: 'Sweden', vat: '25'},
  {country: 'Switzerland', vat: '7.7'},
  {country: 'Syria', vat: '11'},
  {country: 'Taiwan', vat: '5'},
  {country: 'Tajikistan', vat: '18'},
  {country: 'Tanzania', vat: '18'},
  {country: 'Thailand', vat: '7'},
  {country: 'Timor-Leste', vat: '0'},
  {country: 'Togo', vat: '18'},
  {country: 'Tonga', vat: '15'},
  {country: 'Trinidad and Tobago', vat: '12.5'},
  {country: 'Tunisia', vat: '19'},
  {country: 'Turkey', vat: '18'},
  {country: 'Turkmenistan', vat: '15'},
  {country: 'Tuvalu', vat: '0'},
  {country: 'Uganda', vat: '18'},
  {country: 'Ukraine', vat: '20'},
  {country: 'United Arab Emirates', vat: '5'},
  {country: 'United Kingdom', vat: '20'},
  {country: 'United States', vat: '0'},
  {country: 'Uruguay', vat: '22'},
  {country: 'Uzbekistan', vat: '15'},
  {country: 'Vanuatu', vat: '15'},
  {country: 'Venezuela', vat: '16'},
  {country: 'Vietnam', vat: '10'},
  {country: 'Yemen', vat: '0'},
  {country: 'Zambia', vat: '16'},
  {country: 'Zimbabwe', vat: '14.5'},
]

export const touristTaxRates = [
  {country: 'Afghanistan', touristTax: '0'},
  {country: 'Albania', touristTax: '1 EUR per person per night'},
  {country: 'Algeria', touristTax: '0'},
  {country: 'American Samoa', touristTax: '0'},
  {country: 'Andorra', touristTax: '2 EUR per person per night'},
  {country: 'Angola', touristTax: '0'},
  {country: 'Anguilla', touristTax: '10% on room rate'},
  {country: 'Antarctica', touristTax: '0'},
  {country: 'Antigua and Barbuda', touristTax: '3 USD per person per night'},
  {
    country: 'Argentina',
    touristTax: '1 USD per person per night in major cities',
  },
  {country: 'Armenia', touristTax: '0'},
  {country: 'Aruba', touristTax: '9.5% on room rate'},
  {country: 'Australia', touristTax: '0'},
  {
    country: 'Austria',
    touristTax: '1-3 EUR per person per night (varies by region)',
  },
  {country: 'Azerbaijan', touristTax: '1.1 AZN per person per night'},
  {country: 'Bahamas', touristTax: '10% on room rate'},
  {country: 'Bahrain', touristTax: '0'},
  {country: 'Bangladesh', touristTax: '0'},
  {country: 'Barbados', touristTax: '10% on room rate'},
  {country: 'Belarus', touristTax: '0'},
  {
    country: 'Belgium',
    touristTax: '2-5 EUR per room per night (varies by city)',
  },
  {country: 'Belize', touristTax: '9% on room rate'},
  {country: 'Benin', touristTax: '0'},
  {country: 'Bermuda', touristTax: '4.5% on room rate'},
  {
    country: 'Bhutan',
    touristTax: '200-250 USD per day (Sustainable Development Fee)',
  },
  {country: 'Bolivia', touristTax: '0'},
  {
    country: 'Bosnia and Herzegovina',
    touristTax: '1-2 EUR per person per night',
  },
  {
    country: 'Botswana',
    touristTax: '10 USD per person per night (Tourism Development Levy)',
  },
  {
    country: 'Brazil',
    touristTax: 'Varies by city, typically 2-5 BRL per person per night',
  },
  {country: 'Brunei Darussalam', touristTax: '0'},
  {
    country: 'Bulgaria',
    touristTax: '0.5-1.5 EUR per person per night (varies by region)',
  },
  {
    country: 'Canada',
    touristTax: 'Varies by city, typically 3-5% on room rate',
  },
  {country: 'Cayman Islands', touristTax: '13% on room rate'},
  {country: 'China', touristTax: '0'},
  {country: 'Colombia', touristTax: '0'},
  {
    country: 'Costa Rica',
    touristTax: '13% on room rate (VAT included as tourist tax)',
  },
  {country: 'Croatia', touristTax: '1-2 EUR per person per night'},
  {
    country: 'Czech Republic',
    touristTax: '2 EUR per person per night in Prague',
  },
  {country: 'Denmark', touristTax: '0'},
  {country: 'Dominican Republic', touristTax: '10% on room rate'},
  {country: 'Ecuador', touristTax: '0'},
  {country: 'Egypt', touristTax: '1-3% on room rate'},
  {country: 'Estonia', touristTax: '0'},
  {country: 'Finland', touristTax: '0'},
  {
    country: 'France',
    touristTax:
      '0.2-4.2 EUR per person per night (varies by city and accommodation type)',
  },
  {
    country: 'Germany',
    touristTax:
      '5% on room rate or 1-5 EUR per person per night (varies by city)',
  },
  {
    country: 'Greece',
    touristTax: '0.5-4 EUR per room per night (based on hotel classification)',
  },
  {
    country: 'Hungary',
    touristTax: '4% on room rate or fixed rates (varies by city)',
  },
  {country: 'Iceland', touristTax: '0'},
  {country: 'India', touristTax: '5-18% (GST, depending on room price)'},
  {country: 'Indonesia', touristTax: '10% on room rate in major tourist areas'},
  {
    country: 'Italy',
    touristTax:
      '1-7 EUR per person per night (varies by city and accommodation)',
  },
  {
    country: 'Japan',
    touristTax:
      '100-500 JPY per person per night (varies by city and room rate)',
  },
  {country: 'Kenya', touristTax: '2 USD per person per night'},
  {country: 'Malaysia', touristTax: '10 MYR per room per night'},
  {country: 'Malta', touristTax: '0.50 EUR per person per night (max 5 EUR)'},
  {
    country: 'Mexico',
    touristTax: '3-4% on room rate in popular tourist destinations',
  },
  {
    country: 'Netherlands',
    touristTax:
      '3-7% on room rate or fixed amount per person per night (varies by city)',
  },
  {country: 'New Zealand', touristTax: '35 NZD (International Visitor Levy)'},
  {country: 'Norway', touristTax: '0'},
  {
    country: 'Portugal',
    touristTax: '1-2 EUR per person per night (varies by city)',
  },
  {
    country: 'Spain',
    touristTax: '0.5-4 EUR per person per night (varies by region)',
  },
  {country: 'Sweden', touristTax: '0'},
  {
    country: 'Switzerland',
    touristTax: '2-5 CHF per person per night (varies by city)',
  },
  {
    country: 'Thailand',
    touristTax: '300 THB per person (one-time fee starting in 2024)',
  },
  {
    country: 'United Arab Emirates',
    touristTax: '10-20 AED per room per night (varies by emirate)',
  },
  {
    country: 'United Kingdom',
    touristTax: '2-5 GBP per room per night (varies by city)',
  },
  {
    country: 'United States',
    touristTax: 'Varies by state, typically 5-15% on room rate',
  },
  {country: 'Vietnam', touristTax: '0'},
  {country: 'Zimbabwe', touristTax: '2% on room rate'},
]
