export const ACCESS_CREDENTIAL_STATUS = Object.freeze({
  PENDING: "PENDING",
  CREATED: "CREATED",
  SCHEDULED: "SCHEDULED",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});
