export const MAX_WEBSITE_CONFIGURABLE_AMENITIES = 10;
export const MAX_FEATURED_WEBSITE_AMENITIES = 6;
export const WEBSITE_AMENITY_FALLBACK_CATEGORY = "Other";
export const DEFAULT_WEBSITE_AMENITY_LABEL = "New amenity";
