import Ionicons from "react-native-vector-icons/Ionicons";
import MaterialCommunityIcons from "react-native-vector-icons/MaterialCommunityIcons";
import FontAwesome from "react-native-vector-icons/FontAwesome";
import FontAwesome5 from "react-native-vector-icons/FontAwesome5";
import React from "react";
import MaterialIcons from "react-native-vector-icons/MaterialIcons";

/**
 * Amenities icons for accommodations
 */

const DEFAULT_COLOR = "green";
const DEFAULT_SIZE = 24;

const FeatureIcons = {
    'Wi-Fi': <Ionicons name="wifi" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'One guest': <MaterialCommunityIcons name="account" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Two guests': <MaterialCommunityIcons name="account-multiple" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Multiple guests': <MaterialCommunityIcons name="account-group" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bedroom': <MaterialIcons name="bedroom-parent" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bed': <MaterialCommunityIcons name="bed" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Single bed': <MaterialCommunityIcons name="bed-queen" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'King bed': <MaterialCommunityIcons name="bed-king" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Air conditioning': <MaterialCommunityIcons name="air-conditioner" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Heating': <MaterialCommunityIcons name="fire" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'TV with cable/satellite': <Ionicons name="tv-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Hot water': <MaterialCommunityIcons name="water-boiler" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Towels': <FontAwesome name="bath" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bed linens': <Ionicons name="bed-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Extra pillows and blankets': <Ionicons name="bed-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Toilet paper': <MaterialCommunityIcons name="paper-roll-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Soap and shampoo': <MaterialCommunityIcons name="bottle-soda-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Refrigerator': <MaterialCommunityIcons name="fridge-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Microwave': <MaterialCommunityIcons name="microwave" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Oven': <MaterialCommunityIcons name="stove" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Stove': <MaterialCommunityIcons name="fire" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Dishwasher': <MaterialCommunityIcons name="dishwasher" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Coffee maker': <MaterialCommunityIcons name="coffee-maker" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Toaster': <MaterialCommunityIcons name="toaster" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Basic cooking essentials': <MaterialCommunityIcons name="food" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Dishes and silverware': <MaterialCommunityIcons name="silverware-fork-knife" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Glasses and mugs': <MaterialCommunityIcons name="glass-cocktail" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Cutting board and knives': <MaterialCommunityIcons name="knife" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Blender': <MaterialCommunityIcons name="blender" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Kettle': <MaterialCommunityIcons name="kettle-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Hair dryer': <MaterialCommunityIcons name="hair-dryer" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Shower gel': <MaterialCommunityIcons name="shower" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Conditioner': <MaterialCommunityIcons name="spray-bottle" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Body lotion': <MaterialCommunityIcons name="bottle-soda-classic-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'First aid kit': <MaterialCommunityIcons name="medical-bag" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Hangers': <MaterialCommunityIcons name="hanger" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Iron and ironing board': <MaterialCommunityIcons name="iron" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Closet/drawers': <Ionicons name="folder-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Alarm clock': <Ionicons name="alarm-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Sofa': <MaterialCommunityIcons name="sofa" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Armchairs': <MaterialCommunityIcons name="seat-recline-normal" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Coffee table': <MaterialCommunityIcons name="table-furniture" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Books and magazines': <MaterialCommunityIcons name="book-open-variant" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Board games': <MaterialCommunityIcons name="chess-king" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Smart TV': <Ionicons name="tv" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Streaming services': <Ionicons name="tv-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bluetooth speaker': <Ionicons name="bluetooth" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Universal chargers': <MaterialCommunityIcons name="cellphone-charging" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Work desk and chair': <MaterialCommunityIcons name="desk" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Smoke detector': <MaterialCommunityIcons name="smoke-detector" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Carbon monoxide detector': <MaterialCommunityIcons name="molecule-co2" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Fire extinguisher': <MaterialCommunityIcons name="fire-extinguisher" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Lock on bedroom door': <Ionicons name="lock-closed-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'High chair': <MaterialCommunityIcons name="chair-rolling" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Crib': <MaterialCommunityIcons name="cradle-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Children\'s books and toys': <FontAwesome5 name="baby" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Baby safety gates': <MaterialCommunityIcons name="gate" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Baby bath': <MaterialCommunityIcons name="bathtub-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Baby monitor': <Ionicons name="tv-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Baby seat': <MaterialCommunityIcons name="baby-carriage" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Washer and dryer': <MaterialCommunityIcons name="washing-machine" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Laundry detergent': <MaterialCommunityIcons name="bottle-soda-classic-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Clothes drying rack': <FontAwesome name="sun-o" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Keyless entry': <Ionicons name="key-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Self-check-in': <Ionicons name="checkmark-circle-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Local maps and guides': <Ionicons name="map-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Luggage drop-off allowed': <MaterialCommunityIcons name="bag-suitcase" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Parking space': <MaterialCommunityIcons name="parking" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'EV charger': <MaterialCommunityIcons name="car-electric" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Step-free access': <FontAwesome name="wheelchair" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Wide doorways': <MaterialCommunityIcons name="door" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Accessible-height bed': <FontAwesome name="wheelchair" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Accessible-height toilet': <MaterialCommunityIcons name="toilet" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bathroom': <MaterialCommunityIcons name="bathtub" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Shower chair': <MaterialCommunityIcons name="shower" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Recycling bins': <MaterialCommunityIcons name="recycle" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Energy-efficient appliances': <Ionicons name="battery-charging" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Solar panels': <MaterialCommunityIcons name="solar-power" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Composting bin': <MaterialCommunityIcons name="recycle" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Patio or balcony': <MaterialCommunityIcons name="balcony" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Outdoor furniture': <MaterialCommunityIcons name="sofa-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Grill': <MaterialCommunityIcons name="grill" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Fire pit': <MaterialCommunityIcons name="fire" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Pool': <MaterialCommunityIcons name="pool" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Hot tub': <MaterialCommunityIcons name="hot-tub" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Garden or backyard': <MaterialCommunityIcons name="flower" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bicycle': <MaterialCommunityIcons name="bike" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Outdoor shower': <MaterialCommunityIcons name="shower-head" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bimini': <MaterialCommunityIcons name="umbrella" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'External table': <MaterialCommunityIcons name="table" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'External speakers': <MaterialCommunityIcons name="speaker" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Teak deck': <MaterialCommunityIcons name="texture-box" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bow sundeck': <MaterialCommunityIcons name="weather-sunny" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Aft sundeck': <MaterialCommunityIcons name="weather-sunny" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bathing Platform': <MaterialCommunityIcons name="beach" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bathing ladder': <MaterialCommunityIcons name="ladder" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Bow thruster': <MaterialCommunityIcons name="anchor" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Electric windlass': <MaterialCommunityIcons name="anchor" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Autopilot': <MaterialCommunityIcons name="steering" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'GPS': <MaterialCommunityIcons name="satellite-uplink" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Depth sounder': <MaterialCommunityIcons name="water" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'VHF': <MaterialCommunityIcons name="radio" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Guides & Maps': <MaterialCommunityIcons name="map-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Snorkeling equipment': <MaterialCommunityIcons name="diving-snorkel" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Fishing equipment': <MaterialCommunityIcons name="fish" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Diving equipment': <MaterialCommunityIcons name="diving-scuba-tank" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Water skis': <MaterialCommunityIcons name="water" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Monoski': <MaterialCommunityIcons name="ski-water" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Wakeboard': <MaterialCommunityIcons name="ski-water" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Towable Tube': <MaterialCommunityIcons name="lifebuoy" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Inflatable banana': <MaterialCommunityIcons name="water" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Kneeboard': <MaterialCommunityIcons name="kayaking" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Cleaning service': <MaterialCommunityIcons name="broom" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Personal trainer': <MaterialCommunityIcons name="dumbbell" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Private chef': <MaterialCommunityIcons name="chef-hat" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Grocery delivery': <MaterialCommunityIcons name="shopping" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Concierge service': <MaterialCommunityIcons name="broom" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Airport shuttle': <MaterialCommunityIcons name="bus" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Massage therapist': <MaterialCommunityIcons name="account-outline" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
    'Housekeeping': <MaterialCommunityIcons name="broom" size={DEFAULT_SIZE} color={DEFAULT_COLOR}/>,
};

export default FeatureIcons;