projects:
  domits:
    schemaPath: amplify/backend/api/domits/build/schema.graphql
    includes:
      - shared/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: shared/graphql
        region: eu-north-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
